fix results page mobile styling and fonts
lebanon-relief-project/LRP-web-app pull request #100
Opened 2021-02-18 16:35 UTC by MadelinTom

https://trello.com/c/2toRvPAK/127-mobile-styling-of-the-page-of-results

2021-02-18 18:58 UTC, matejoslav commented
@MadelinTom looks good but we should be using styled components everywhere

2021-02-18 18:59 UTC, matejoslav requested changes
see above

2021-02-25 10:58 UTC, matejoslav requested changes
Found a small typo, also do we still need the font changes? Maybe if we merge dev into the branch we can get rid of them

2021-02-25 10:58 UTC, matejoslav commented on web-app/src/components/resultsPage/ResultCard.js
> +          <p style={{ margin: "10px", fontFamily: "Rleway", fontSize: "16px" }}>
typo in fontFamily entry

2021-02-26 14:07 UTC, matejoslav approved these changes

2021-02-28 12:05 UTC, merged

2021-02-28 12:18 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210228-121757 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210228-121757") to [dev](https://console.bluemix.net/apps/4a65172b-6ccd-4969-a77b-771a8adf5eb5?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit abbe7043eb1aaf33791d9f87080c2a579107a4db

2021-03-02 13:06 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622") to [test](https://console.bluemix.net/apps/bef762e5-4952-4e16-a258-78b99b9fb66d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit abbe7043eb1aaf33791d9f87080c2a579107a4db