fixed styling on ipad and changed text
lebanon-relief-project/LRP-web-app pull request #107
Opened 2021-02-25 01:45 UTC by matejoslav

https://trello.com/c/aQUqy9pH/213-traumatic-events-section-looks-bad-on-tablet

https://trello.com/c/xcHVw6TN/165-traumatic-events-text-in-taking-the-test-page

2021-02-25 09:51 UTC, MadelinTom commented
Is the paragraph here meant to be aligned to the left? 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/20341285/109135442-fc5c6480-774e-11eb-93cb-b9a740164f02.png">

2021-02-25 10:55 UTC, matejoslav commented
Will ask Tag

2021-02-28 12:08 UTC, nicholasmorgan requested changes
Needs fixing on mobile view

2021-03-01 15:12 UTC, MadelinTom commented
FeelingSection.js line 28: max-width 90% here would make the paragraph the same width as the header text. We should ask design what they want this to look like.

2021-03-02 15:03 UTC, MadelinTom commented on web-app/src/components/FeelingsSection.js
>    margin: 0 16.7%;
We need to remove width: 50% here and make it maybe width 95% to match designs:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/20341285/109667881-813ce900-7b68-11eb-90f9-65f21b59aac9.png">

2021-03-02 15:04 UTC, MadelinTom requested changes
See comment

2021-03-07 13:46 UTC, nicholasmorgan approved these changes

2021-03-07 13:48 UTC, merged

2021-03-07 13:59 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210307-135930 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210307-135930") to [dev](https://console.bluemix.net/apps/2ecd7e18-16aa-47d3-8830-a9d5742686d3?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 4569a14c6cf9a852180fe34485f777917f83a8e9

2021-03-07 16:58 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210307-165809 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210307-165809") to [test](https://console.bluemix.net/apps/24633070-15da-462f-b17f-f8e232e0b152?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 4569a14c6cf9a852180fe34485f777917f83a8e9

2021-03-07 17:54 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210307-175452 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210307-175452") to [prod](https://console.bluemix.net/apps/60de5256-5a33-4b93-8cb2-8eb23fcb0f7b?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 4569a14c6cf9a852180fe34485f777917f83a8e9