Like to help modal
lebanon-relief-project/LRP-web-app pull request #50
Opened 2021-01-09 15:10 UTC by nicholasmorgan

2021-01-10 22:58 UTC, matejoslav requested changes
Modal opens everytime you load the page.

Tests are missing to test that clicking the button opens the modal and clicking close button closes the modal.

![image](https://user-images.githubusercontent.com/8973672/104137738-f412ba80-5396-11eb-8d4a-cadd2674168e.png)
The X appears low resolution, we should get .svg file for this.

Would be nice if clicking outside of the modal closed it.

Modal itself looks nice.

2021-01-10 22:59 UTC, matejoslav commented on web-app/src/components/HelpSection.js
> +  const [likeToHelpModalVisible, setLikeToHelpModalVisible] = useState(true);
Should be false by default I think

2021-01-11 11:21 UTC, nicholasmorgan commented on web-app/src/components/HelpSection.js
> +  const [likeToHelpModalVisible, setLikeToHelpModalVisible] = useState(true);
updated

2021-01-12 09:00 UTC, nicholasmorgan commented
Added the above

2021-01-12 09:02 UTC, nicholasmorgan commented
Regarding adding being able to close the modal by clicking out of it, I think that should be added as a separate ticket

2021-01-12 11:50 UTC, MadelinTom commented
Looks good!

2021-01-12 11:54 UTC, matejoslav approved these changes

2021-01-12 11:54 UTC, merged

2021-01-12 12:07 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210112-120714 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210112-120714") to [dev](https://console.bluemix.net/apps/b98a4dd3-7816-44c4-9933-d50225ef97ee?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 2af43830c2462dc51a2bdce552512168b102b851

2021-01-19 17:45 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210119-174451 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210119-174451") to [test](https://console.bluemix.net/apps/ffe68851-6e56-40b0-80a3-554fcbfafe9d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 2af43830c2462dc51a2bdce552512168b102b851

2021-02-05 15:27 UTC, arnoldst commented
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747") to [test](https://console.bluemix.net/apps/1d38058e-0941-478d-ab73-1c5c09e8e146?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 2af43830c2462dc51a2bdce552512168b102b851